import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    export: 'Export',
    import: 'Import',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    actions: 'Actions',

    // Employee Portal
    enterId: 'Enter Employee ID',
    login: 'Login',
    attemptsRemaining: 'attempts remaining',
    lockoutMessage: 'Too many failed attempts. Please wait 10 minutes.',
    employeeNotFound: 'Employee not found',
    invalidId: 'Invalid employee ID',
    idHelpText: 'Enter your employee ID to access your profile',
    searchEmployee: 'Search Employee',
    searchEmployeeHint: 'Enter employee name or ID to view profile',
    employeeIdOrName: 'Employee Name or ID',
    searchPlaceholder: 'Search by name or employee ID...',
    employeeId: 'Employee ID',
    arabicName: 'Arabic Name',
    englishName: 'English Name',
    birthdate: 'Birthdate',
    fullName: 'Full Name',
    personalInfo: 'Personal Information',
    employmentInfo: 'Employment Details',
    contactInfo: 'Contact Information',
    jobTitle: 'Job Title',
    jobTitleAr: 'Job Title (Arabic)',
    jobTitleEn: 'Job Title (English)',
    department: 'Department',
    email: 'Email',
    sector: 'Sector',
    hireDate: 'Hire Date',
    address: 'Address',
    phone: 'Phone',
    employmentStatus: 'Employment Status',
    active: 'Active',
    inactive: 'Inactive',
    resigned: 'Resigned',
    profilePicture: 'Profile Picture',
    fromUrl: 'From URL',
    qrCode: 'QR Code',
    workShift: 'Work Shift',
    bloodType: 'Blood Type',
    emergencyContact: 'Emergency Contact',
    notes: 'Notes',
    insuranceNumber: 'Insurance Number',
    directManager: 'Direct Manager',
    certifications: 'Certifications',
    category: 'Category',
    bank: 'Bank',
    bankAccount: 'Bank Account',
    attendanceBase: 'Attendance Base',
    route: 'Route',
    education: 'Education',
    graduationYear: 'Graduation Year',
    employmentStartDate: 'Employment Start Date',
    experience: 'Experience',
    years: 'Years',
    months: 'Months',
    days: 'Days',
    additionalInfo: 'Additional Information',
    copyId: 'Copy ID',
    languages: 'Languages',
    selectLanguage: 'Select Language',
    proficiencyLevel: 'Proficiency Level',
    addLanguage: 'Add Language',
    removeLanguage: 'Remove Language',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    fluent: 'Fluent',
    native: 'Native',
    documents: 'Documents',
    uploadDocument: 'Upload Document',
    addDocument: 'Add Document',
    removeDocument: 'Remove Document',
    documentName: 'Document Name',
    documentType: 'Document Type',
    uploadDate: 'Upload Date',
    noDocuments: 'No documents uploaded',
    viewDocument: 'View',
    supportedFormats: 'Supported formats: PDF, Word, Excel, Images (JPG, PNG, etc.)',
    printProfile: 'Print Profile',
    downloadPdf: 'Download PDF',

    // Admin
    adminLogin: 'Admin Login',
    username: 'Username',
    password: 'Password',
    dashboard: 'Dashboard',
    employees: 'Employees',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    deleteEmployee: 'Delete Employee',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    inactiveEmployees: 'Inactive Employees',
    departments: 'Departments',
    branches: 'Branches',
    employeesByDepartment: 'Employees by Department',
    employeesByBranch: 'Employees by Branch',
    activityLog: 'Activity Log',
    backup: 'Backup',
    restore: 'Restore',
    logout: 'Logout',
    welcome: 'Welcome',
    welcomeHint: 'Sign in to access employee data',
    confirmDelete: 'Confirm Delete',
    deleteConfirmMessage: 'Are you sure you want to delete this employee? This action cannot be undone.',
    sections: 'Sections',
    sectionsSubtitle: 'Manage sections that employees belong to',
    addSection: 'Add New Section',
    users: 'Users',
    manageUsers: 'Manage system admin users and credentials',
    addUser: 'Add User',
    addNewUser: 'Add New User',
    editUser: 'Edit User',
    editUsername: 'Edit Username',
    newUsername: 'New Username',
    enterUsernamePlaceholder: 'Enter username...',
    role: 'Role',
    selectRole: 'User Role',
    adminRole: 'Administrator (Admin)',
    userRole: 'Regular User (User)',
    superAdmin: 'Super Admin',
    adminUser: 'Admin',
    passwordStatus: 'Password Status',
    defaultPasswordBadge: 'Default Password (123456)',
    updatedPasswordBadge: 'Updated',
    createdAt: 'Created At',
    noUsers: 'No users found',
    defaultPasswordInfoTitle: 'Default Password: 123456',
    defaultPasswordInfoDesc: 'The user will be prompted to change their password via a popup modal on their first login.',
    resetPasswordDefault: 'Reset Password to Default',
    resetPasswordConfirmTitle: 'Reset Password to Default',
    resetPasswordConfirmMessage: 'Are you sure you want to reset the password for user "{username}" to default (123456)?',
    resetPasswordSubtext: 'The user will be required to set a new password on their next login.',
    resetPasswordSuccess: 'Password successfully reset to default (123456)',
    deleteUserConfirm: 'Are you sure you want to delete user "{username}"? This action cannot be undone.',
    forcedPasswordTitle: 'Change Initial Password',
    forcedPasswordSubtitle: 'Your account requires setting a new password before continuing.',
    newPasswordPlaceholder: 'Enter new password...',
    confirmPasswordPlaceholder: 'Confirm new password...',
    saveAndLogin: 'Save Password & Continue',
    backupAndRestore: 'Backup & Restore',
    backupSubtitle: 'Manage system database backups, export data, and restore from files',
    downloadFullBackup: 'Download Full Backup (.db)',
    downloadJsonBackup: 'Export Data as JSON (.json)',
    restoreBackup: 'Restore Database',
    restoreHint: 'Select a valid .db backup file to restore system database',
    selectBackupFile: 'Select Backup File',
    confirmRestoreTitle: 'Confirm Database Restore',
    confirmRestoreMessage: 'Restoring a backup will overwrite all current system data. Are you sure you want to proceed?',
    restoreSuccess: 'Database restored successfully',
    backupHistory: 'Backup Activity History',
    newUser: 'New Admin User',
    sectionNameEn: 'Section Name (English)',
    sectionNameAr: 'Section Name (Arabic)',
    sectionNameEnPlaceholder: 'e.g. IT, HR, Finance',
    sectionNameArPlaceholder: 'مثال: تقنية المعلومات، الموارد البشرية',
    noSections: 'No sections found',
    deleteSectionConfirm: 'Are you sure you want to delete this section? This action cannot be undone.',

    // Custom fields
    customFields: 'Custom Fields',
    customFieldsSubtitle: 'Manage custom fields that appear in employee profiles and Excel export',
    addCustomField: 'Add New Custom Field',
    editCustomField: 'Edit Custom Field',
    fieldNameEn: 'Field Title (English)',
    fieldNameAr: 'Field Title (Arabic)',
    fieldNameEnPlaceholder: 'e.g. Blood Type, National ID',
    fieldNameArPlaceholder: 'مثال: فصيلة الدم، الرقم القومي',
    customFieldType: 'Field Type',
    customFieldTypeText: 'Text',
    customFieldTypeNumber: 'Number',
    customFieldTypeDate: 'Date',
    customFieldTypeTextarea: 'Long Text',
    customFieldTypeSelect: 'Dropdown',
    fieldOptions: 'Options (comma separated)',
    fieldOptionsPlaceholder: 'e.g. Option 1, Option 2, Option 3',
    noCustomFields: 'No custom fields created yet',
    deleteCustomFieldConfirm: 'Are you sure you want to delete this custom field? The saved values in employee profiles will no longer be displayed.',
    customFieldSection: 'Profile Section',

    // Profile sections
    profileSections: 'Profile Sections',
    profileSectionsSubtitle: 'Manage the main profile section titles and their layout',
    addProfileSection: 'Add New Profile Section',
    editProfileSection: 'Edit Profile Section',
    profileSectionNameEnPlaceholder: 'e.g. Certificates, Social Links',
    profileSectionNameArPlaceholder: 'مثال: الشهادات، روابط التواصل',
    sectionColumn: 'Column',
    sectionColumnLeft: 'Column 1',
    sectionColumnRight: 'Column 2',
    sectionSortOrder: 'Order',
    sectionType: 'Type',
    sectionBuiltin: 'Built-in',
    sectionCustom: 'Custom',
    sectionBuiltinDeleteError: 'Built-in sections cannot be deleted',
    noProfileSections: 'No profile sections found',
    deleteProfileSectionConfirm: 'Are you sure you want to delete this profile section? Its custom fields will be moved back to the default section.',

    // Section fields
    sectionFields: 'Section Fields',
    sectionFieldsSubtitle: 'Add or remove the fields shown in each profile section (like address, phone, email)',
    addReadyField: 'Add Ready Field',
    addReadyFieldPlaceholder: 'Select a ready field to add',
    noReadyFields: 'All ready fields have been added to this section',
    fieldSection: 'Section',
    fieldVisible: 'Visible',
    fieldHidden: 'Hidden',
    builtinField: 'Ready field',
    noSectionFields: 'No fields in this section yet',
    deleteSectionFieldConfirm: 'Are you sure you want to delete this field from the section? It will no longer be shown or edited in employee forms.',
    fieldTypeStatus: 'Status',
    fieldAlreadyAdded: 'This field is already added',

    // Settings
    accountSettings: 'Account Settings',
    changeCredentials: 'Change Credentials',
    usernameUpdated: 'Username updated successfully',
    passwordUpdated: 'Password updated successfully',
    currentPasswordRequired: 'Current password is required',
    newPasswordRequired: 'New password is required',
    usernameTaken: 'Username already taken',
    incorrectPassword: 'Current password is incorrect',
    chooseDesign: 'Choose Design',

    // Form fields
    firstName: 'First Name',
    lastName: 'Last Name',
    middleName: 'Middle Name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    dateOfBirth: 'Date of Birth',
    maritalStatus: 'Marital Status',
    single: 'Single',
    married: 'Married',
    divorced: 'Divorced',
    widowed: 'Widowed',
    nationality: 'Nationality',
    passportNumber: 'Passport Number',
    visaStatus: 'Visa Status',
    visaExpiry: 'Visa Expiry',
    salary: 'Salary',
    bankName: 'Bank Name',
    contractStart: 'Contract Start',
    contractEnd: 'Contract End',
    contractType: 'Contract Type',
    permanent: 'Permanent',
    contract: 'Contract',
    part_time: 'Part Time',
    temporary: 'Temporary',
    probation: 'Probation',
    leaveBalance: 'Leave Balance',
    annualLeave: 'Annual Leave',
    sickLeave: 'Sick Leave',
    personalLeave: 'Personal Leave',
    submit: 'Submit',
    reset: 'Reset',
    requiredField: 'Required field',
    invalidPhone: 'Invalid phone number',
    passwordMinLength: 'Password must be at least 6 characters',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember me',
    logoutConfirmMsg: 'Are you sure you want to log out?',
    forgotPasswordTitle: 'Forgot Password?',
    forgotPasswordStep1: 'Enter your username to continue',
    forgotPasswordStep2: 'Answer the security question and enter a new password',
    continueBtn: 'Continue',
    searchingUser: 'Searching...',
    securityQuestion: 'Security Question:',
    answer: 'Answer',
    answerPlaceholder: 'Type your answer here...',
    securityQ1: "What is your mother's name?",
    securityQ2: "What is your pet's name?",
    securityQ3: "What was the name of your first school?",
    securityQ4: "What is your favorite color?",
    securityQuestionOptionalHint: '(Optional) Set a security question for password recovery',
    chooseQuestion: 'Choose a Question',
    chooseSecurityQuestion: 'Choose a security question...',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    savingPassword: 'Saving...',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    changeUsername: 'Change Username',
    age: 'Age',

    // Navigation
    home: 'Home',
    myProfile: 'My Profile',
    myDepartment: 'My Department',
    myTeam: 'My Team',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    contactUs: 'Contact Us',
    feedback: 'Feedback',
    notifications: 'Notifications',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',

    // Dashboard
    overview: 'Overview',
    recentActivity: 'Recent Activity',
    statistics: 'Statistics',
    reports: 'Reports',
    manageEmployees: 'Manage Employees',
    departmentDistribution: 'Department Distribution',
    branchDistribution: 'Branch Distribution',
    monthlyJoinings: 'Monthly Joinings',
    employeeGrowth: 'Employee Growth',

    // Table
    noData: 'No data available',
    showing: 'Showing',
    of: 'of',
    entries: 'entries',
    rowsPerPage: 'Rows per page',
    page: 'Page',
    first: 'First',
    last: 'Last',

    // Messages
    loginSuccess: 'Login successful',
    loginFailed: 'Login failed',
    changePasswordFirst: 'Change Your Password',
    changePasswordFirstHint: 'You must change your password before continuing',
    newPassword: 'New Password',
    passwordMismatch: 'Passwords do not match',
    passwordChanged: 'Password changed successfully',
    cannotPreview: 'Cannot preview this file',
    openFile: 'Open File',
    noFileAttached: 'No file attached',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Failed to save',
    deleteSuccess: 'Deleted successfully',
    deleteFailed: 'Failed to delete',
    updateSuccess: 'Updated successfully',
    updateFailed: 'Failed to update',
    createSuccess: 'Created successfully',
    createFailed: 'Failed to create',
    importSuccess: 'Imported successfully',
    importFailed: 'Failed to import',
    exportSuccess: 'Exported successfully',
    exportFailed: 'Failed to export',
    backupSuccess: 'Backup created successfully',
    backupFailed: 'Failed to create backup',
    restoreFailed: 'Failed to restore',

    networkError: 'Network error. Please check your connection.',
    serverError: 'Server error. Please try again later.',
    unauthorized: 'Unauthorized. Please login again.',
    forbidden: 'You do not have permission to perform this action.',
    notFound: 'Resource not found.',

    // Time
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',

    // Auth
    sessionExpired: 'Your session has expired. Please login again.',
    sessionTimeout: 'Session Timeout',
    sessionTimeoutHint: 'You have been inactive. You will be logged out due to inactivity.',
    stayLoggedIn: 'Stay Logged In',
    invalidCredentials: 'Invalid username or password',
    accountLocked: 'Account locked. Please contact administrator.',

    // QR Code
    scanQrCode: 'Scan QR Code',
    qrCodeDescription: 'Scan this QR code to quickly access employee information',
    downloadQrCode: 'Download QR Code',

    // PDF
    generatePdf: 'Generate PDF',
    pdfGenerated: 'PDF generated successfully',
    pdfFailed: 'Failed to generate PDF',

    // Print
    printId: 'Print ID Card',
    idCard: 'ID Card',
    companyLogo: 'Company Logo',
    employeeSignature: 'Employee Signature',
    validUntil: 'Valid Until',

    // Charts
    chart: 'Chart',
    barChart: 'Bar Chart',
    pieChart: 'Pie Chart',
    lineChart: 'Line Chart',
    noDataAvailable: 'No data available for this chart',

    // Date & Time
    date: 'Date',
    time: 'Time',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    start: 'Start',
    end: 'End',

    // Validation
    fieldRequired: 'This field is required',
    invalidFormat: 'Invalid format',
    tooShort: 'Too short',
    tooLong: 'Too long',
    minValue: 'Minimum value is {min}',
    maxValue: 'Maximum value is {max}',

    // Status
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    completed: 'Completed',
    inProgress: 'In Progress',
    onHold: 'On Hold',

    // Misc
    all: 'All',
    none: 'None',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    noResults: 'No results found',
    tryAgain: 'Try Again',
    viewAll: 'View All',
    viewDetails: 'View Details',
    collapse: 'Collapse',
    expand: 'Expand',
    refresh: 'Refresh',
    retry: 'Retry',
    undo: 'Undo',
    redo: 'Redo',
    copy: 'Copy',
    paste: 'Paste',
    cut: 'Cut',
    select: 'Select',
    deselect: 'Deselect',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    dragToReorder: 'Drag to reorder',
    moreOptions: 'More options',
    lessOptions: 'Less options',
    showMore: 'Show more',
    showLess: 'Show less',
    details: 'Details',
    summary: 'Summary',
    fullView: 'Full View',
    compactView: 'Compact View',
    listView: 'List View',
    gridView: 'Grid View',
    sortBy: 'Sort by',
    ascending: 'Ascending',
    descending: 'Descending',
    groupBy: 'Group by',
    enableNotifications: 'Enable Notifications',
    disableNotifications: 'Disable Notifications',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemDefault: 'System Default',
    english: 'English',
    arabic: 'Arabic',
    french: 'French',
    employeePortal: 'Employee Portal',
    language: 'Language',
    theme: 'Theme',
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    privacySettings: 'Privacy Settings',
    securitySettings: 'Security Settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    updateProfile: 'Update Profile',
    uploadPhoto: 'Upload Photo',
    removePhoto: 'Remove Photo',
    cropPhoto: 'Crop Photo',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    rotateLeft: 'Rotate Left',
    rotateRight: 'Rotate Right',
    resetZoom: 'Reset Zoom',
    fitToScreen: 'Fit to Screen',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit Fullscreen',
    minimize: 'Minimize',
    maximize: 'Maximize',
    restoreDefault: 'Restore Default',
    applyChanges: 'Apply Changes',
    discardChanges: 'Discard Changes',
    unsavedChanges: 'You have unsaved changes',
    areYouSure: 'Are you sure?',
    thisActionCannotBeUndone: 'This action cannot be undone.',
    permanentAction: 'This is a permanent action.',
    proceedWithCaution: 'Proceed with caution.',
    enterPasswordToConfirm: 'Enter your password to confirm.',
    actionRequiresConfirmation: 'This action requires confirmation.',
    confirmAction: 'Confirm Action',
    cancelAction: 'Cancel Action',
    backToTop: 'Back to Top',
    scrollDown: 'Scroll Down',
    goToPage: 'Go to Page',
    changePage: 'Change Page',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    firstPage: 'First Page',
    lastPage: 'Last Page',
    jumpToPage: 'Jump to Page',
    goTo: 'Go to',
    ofTotalPages: 'of {total} pages',
    selectedRows: '{count} rows selected',
    selectRow: 'Select row',
    deselectRow: 'Deselect row',
    expandRow: 'Expand row',
    collapseRow: 'Collapse row',
    viewRow: 'View row',
    editRow: 'Edit row',
    deleteRow: 'Delete row',
    duplicateRow: 'Duplicate row',
    copyRow: 'Copy row',
    moveRow: 'Move row',
    rowActions: 'Row actions',
    bulkActions: 'Bulk actions',
    noItemsSelected: 'No items selected',
    deleteSelected: 'Delete Selected',
    exportSelected: 'Export Selected',
    printSelected: 'Print Selected',
    selectAction: 'Select an action',
    confirmBulkDelete: 'Are you sure you want to delete the selected items?',
    bulkDeleteSuccess: 'Selected items deleted successfully',
    bulkDeleteFailed: 'Failed to delete selected items',
    bulkExportSuccess: 'Selected items exported successfully',
    bulkExportFailed: 'Failed to export selected items',
    bulkPrintSuccess: 'Selected items sent to printer',
    bulkPrintFailed: 'Failed to print selected items',
  },

  ar: {
    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    print: 'طباعة',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    close: 'إغلاق',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    actions: 'إجراءات',

    // Employee Portal
    enterId: 'أدخل رقم الموظف',
    login: 'تسجيل الدخول',
    attemptsRemaining: 'محاولات متبقية',
    lockoutMessage: 'محاولات كثيرة فاشلة. يرجى الانتظار 10 دقائق.',
    employeeNotFound: 'لم يتم العثور على الموظف',
    invalidId: 'رقم الموظف غير صالح',
    idHelpText: 'أدخل رقم الموظف للوصول إلى ملفك الشخصي',
    profile: 'الملف الشخصي',
    employeeId: 'رقم الموظف',
    arabicName: 'الاسم بالعربية',
    englishName: 'الاسم بالإنجليزية',
    birthdate: 'تاريخ الميلاد',
    fullName: 'الاسم الكامل',
    personalInfo: 'المعلومات الشخصية',
    employmentInfo: 'بيانات التوظيف',
    contactInfo: 'معلومات الاتصال',
    jobTitle: 'المسمى الوظيفي',
    jobTitleAr: 'المسمى الوظيفي (عربي)',
    jobTitleEn: 'المسمى الوظيفي (إنجليزي)',
    department: 'القسم',
    email: 'البريد الإلكتروني',
    sector: 'القطاع',
    hireDate: 'تاريخ التعيين',
    address: 'العنوان',
    phone: 'الهاتف',
    employmentStatus: 'حالة التوظيف',
    active: 'نشط',
    inactive: 'غير نشط',
    resigned: 'مستقيل',
    profilePicture: 'صورة الملف الشخصي',
    fromUrl: 'من رابط',
    qrCode: 'رمز QR',
    workShift: 'وردية العمل',
    bloodType: 'فصيلة الدم',
    emergencyContact: 'جهة اتصال الطوارئ',
    notes: 'ملاحظات',
    insuranceNumber: 'الرقم التأمينى',
    directManager: 'المدير المباشر',
    certifications: 'الشهادات',
    category: 'الكادر',
    bank: 'الصراف',
    bankAccount: 'رقم الحساب',
    attendanceBase: 'قاعدة الحضور والإنصراف',
    route: 'خط السير',
    education: 'المؤهل الدراسي',
    graduationYear: 'سنة التخرج',
    employmentStartDate: 'تاريخ بداية العمل',
    experience: 'الخبرة',
    years: 'سنة',
    months: 'شهر',
    days: 'يوم',
    additionalInfo: 'معلومات إضافية',
    languages: 'اللغات',
    documents: 'المستندات',
    uploadDocument: 'رفع مستند',
    addDocument: 'إضافة مستند',
    removeDocument: 'إزالة المستند',
    documentName: 'اسم المستند',
    documentType: 'نوع المستند',
    uploadDate: 'تاريخ الرفع',
    noDocuments: 'لا توجد مستندات مرفوعة',
    viewDocument: 'فتح',
    supportedFormats: 'الصيغ المدعومة: PDF، Word، Excel، الصور (JPG، PNG، إلخ)',
    selectLanguage: 'اختر اللغة',
    proficiencyLevel: 'مستوى الإتقان',
    addLanguage: 'إضافة لغة',
    removeLanguage: 'إزالة اللغة',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    fluent: 'طلاقة',
    native: 'لغة الأم',
    copyId: 'نسخ الرقم',
    printProfile: 'طباعة الملف الشخصي',
    downloadPdf: 'تنزيل PDF',

    // Admin
    adminLogin: 'تسجيل دخول المدير',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    dashboard: 'لوحة التحكم',
    employees: 'الموظفون',
    addEmployee: 'إضافة موظف',
    editEmployee: 'تعديل موظف',
    deleteEmployee: 'حذف موظف',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفون النشطون',
    inactiveEmployees: 'الموظفون غير النشطين',
    departments: 'الأقسام',
    branches: 'الفروع',
    employeesByDepartment: 'الموظفون حسب القسم',
    employeesByBranch: 'الموظفون حسب الفرع',
    activityLog: 'سجل النشاط',
    backup: 'نسخ احتياطي',
    restore: 'استعادة',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً',
    welcomeHint: 'سجّل الدخول للوصول لبيانات الموظفين',
    confirmDelete: 'تأكيد الحذف',
    deleteConfirmMessage: 'هل أنت متأكد من حذف هذا الموظف؟ لا يمكن التراجع عن هذا الإجراء.',
    sections: 'الأقسام',
    sectionsSubtitle: 'إدارة الأقسام التي ينتمي إليها الموظفون',
    addSection: 'إضافة قسم جديد',
    users: 'المستخدمين',
    manageUsers: 'إدارة مستخدمي النظام وصلاحياتهم',
    addUser: 'إضافة مستخدم',
    addNewUser: 'إضافة مستخدم جديد',
    editUser: 'تعديل المستخدم',
    editUsername: 'تعديل اسم المستخدم',
    newUsername: 'اسم المستخدم الجديد',
    enterUsernamePlaceholder: 'أدخل اسم المستخدم...',
    role: 'الدور',
    selectRole: 'نوع المستخدم / الصلاحية',
    adminRole: 'مسؤول نظام (Admin)',
    userRole: 'مستخدم عادي (User)',
    superAdmin: 'مدير عام (Super Admin)',
    adminUser: 'مستخدم (Admin)',
    passwordStatus: 'حالة كلمة المرور',
    defaultPasswordBadge: 'كلمة مرور افتراضية (123456)',
    updatedPasswordBadge: 'مُحدثة',
    createdAt: 'تاريخ الإنشاء',
    noUsers: 'لا يوجد مستخدمون',
    defaultPasswordInfoTitle: 'كلمة المرور الافتراضية: 123456',
    defaultPasswordInfoDesc: 'سيُطلب من المستخدم تغيير كلمة المرور عبر نافذة منبثقة عند أول تسجيل دخول له.',
    resetPasswordDefault: 'إعادة كلمة السر للديفولت',
    resetPasswordConfirmTitle: 'إعادة كلمة السر للديفولت',
    resetPasswordConfirmMessage: 'هل أنت متأكد من إعادة كلمة السر للمستخدم "{username}" إلى الكلمة الافتراضية (123456)؟',
    resetPasswordSubtext: 'سيُطلب من المستخدم تحديد كلمة مرور جديدة عند تسجيل دخوله القادم.',
    resetPasswordSuccess: 'تم إعادة كلمة المرور للكلمة الافتراضية (123456) بنجاح',
    deleteUserConfirm: 'هل أنت متأكد من حذف المستخدم "{username}"؟ لا يمكن التراجع عن هذا الإجراء.',
    forcedPasswordTitle: 'تغيير كلمة المرور المبدئية',
    forcedPasswordSubtitle: 'حسابك جديد أو تمت إعادة ضبط كلمة المرور له. يرجى كتابة كلمة المرور الجديدة مرتين للاستمرار.',
    newPasswordPlaceholder: 'أدخل كلمة المرور الجديدة...',
    confirmPasswordPlaceholder: 'تأكيد كلمة المرور الجديدة...',
    saveAndLogin: 'حفظ كلمة المرور والدخول',
    backupAndRestore: 'النسخ الاحتياطي والاستعادة',
    backupSubtitle: 'إدارة النسخ الاحتياطية لقاعدة البيانات وتصدير واستعادة البيانات',
    downloadFullBackup: 'تنزيل نسخة احتياطية كاملة (.db)',
    downloadJsonBackup: 'تصدير البيانات بصيغة JSON',
    restoreBackup: 'استعادة نسخة احتياطية',
    restoreHint: 'اختر ملف نسخة احتياطية صيغة .db لإعادة تعيين قاعدة البيانات',
    selectBackupFile: 'اختر ملف النسخة الاحتياطية',
    confirmRestoreTitle: 'تأكيد استعادة قاعدة البيانات',
    confirmRestoreMessage: 'استعادة النسخة الاحتياطية سوف تستبدل كافة البيانات الحالية. هل أنت متأكد من الاستمرار؟',
    restoreSuccess: 'تمت استعادة قاعدة البيانات بنجاح',
    backupHistory: 'سجل عمليات النسخ الاحتياطي والاستعادة',
    newUser: 'مستخدم جديد',
    sectionNameEn: 'اسم القسم (إنجليزي)',
    sectionNameAr: 'اسم القسم (عربي)',
    sectionNameEnPlaceholder: 'مثال: IT, HR, Finance',
    sectionNameArPlaceholder: 'مثال: تقنية المعلومات، الموارد البشرية',
    noSections: 'لا توجد أقسام',
    deleteSectionConfirm: 'هل أنت متأكد من حذف هذا القسم؟ لا يمكن التراجع عن هذا الإجراء.',

    // Custom fields
    customFields: 'الحقول المخصصة',
    customFieldsSubtitle: 'إدارة الحقول المخصصة التي تظهر في ملفات الموظفين وشيت الاكسيل',
    addCustomField: 'إضافة حقل مخصص جديد',
    editCustomField: 'تعديل الحقل المخصص',
    fieldNameEn: 'عنوان الحقل (إنجليزي)',
    fieldNameAr: 'عنوان الحقل (عربي)',
    fieldNameEnPlaceholder: 'مثال: Blood Type, National ID',
    fieldNameArPlaceholder: 'مثال: فصيلة الدم، الرقم القومي',
    customFieldType: 'نوع الحقل',
    customFieldTypeText: 'نص',
    customFieldTypeNumber: 'رقم',
    customFieldTypeDate: 'تاريخ',
    customFieldTypeTextarea: 'نص طويل',
    customFieldTypeSelect: 'قائمة منسدلة',
    fieldOptions: 'الخيارات (مفصولة بفاصلة)',
    fieldOptionsPlaceholder: 'مثال: خيار 1, خيار 2, خيار 3',
    noCustomFields: 'لم يتم إنشاء حقول مخصصة بعد',
    deleteCustomFieldConfirm: 'هل أنت متأكد من حذف هذا الحقل المخصص؟ لن تظهر القيم المحفوظة في ملفات الموظفين بعد الآن.',
    customFieldSection: 'قسم البروفيل',

    // Profile sections
    profileSections: 'أقسام الملف الشخصي',
    profileSectionsSubtitle: 'إدارة العناوين الرئيسية للملف الشخصي وترتيبها',
    addProfileSection: 'إضافة قسم جديد',
    editProfileSection: 'تعديل القسم',
    profileSectionNameEnPlaceholder: 'مثال: Certificates, Social Links',
    profileSectionNameArPlaceholder: 'مثال: الشهادات، روابط التواصل',
    sectionColumn: 'العمود',
    sectionColumnLeft: 'العمود الأول',
    sectionColumnRight: 'العمود الثاني',
    sectionSortOrder: 'الترتيب',
    sectionType: 'النوع',
    sectionBuiltin: 'مدمج',
    sectionCustom: 'مخصص',
    sectionBuiltinDeleteError: 'لا يمكن حذف الأقسام المدمجة',
    noProfileSections: 'لم يتم العثور على أقسام',
    deleteProfileSectionConfirm: 'هل أنت متأكد من حذف هذا القسم؟ سيتم نقل حقوله المخصصة إلى القسم الافتراضي.',

    // Section fields
    sectionFields: 'خانات الأقسام',
    sectionFieldsSubtitle: 'أضف أو احذف الخانات المعروضة في كل قسم (مثل العنوان، الهاتف، البريد)',
    addReadyField: 'إضافة خانة جاهزة',
    addReadyFieldPlaceholder: 'اختر خانة جاهزة لإضافتها',
    noReadyFields: 'تمت إضافة كل الخانات الجاهزة في هذا القسم',
    fieldSection: 'القسم',
    fieldVisible: 'ظاهرة',
    fieldHidden: 'مخفية',
    builtinField: 'خانة جاهزة',
    noSectionFields: 'لا توجد خانات في هذا القسم بعد',
    deleteSectionFieldConfirm: 'هل أنت متأكد من حذف هذه الخانة من القسم؟ لن تظهر أو تُعدل بعد ذلك في نماذج الموظفين.',
    fieldTypeStatus: 'الحالة',
    fieldAlreadyAdded: 'هذه الخانة تمت إضافتها بالفعل',

    // Settings
    accountSettings: 'إعدادات الحساب',
    changeCredentials: 'تغيير بيانات الدخول',
    usernameUpdated: 'تم تحديث اسم المستخدم بنجاح',
    passwordUpdated: 'تم تحديث كلمة المرور بنجاح',
    currentPasswordRequired: 'كلمة المرور الحالية مطلوبة',
    newPasswordRequired: 'كلمة المرور الجديدة مطلوبة',
    usernameTaken: 'اسم المستخدم مستخدم بالفعل',
    incorrectPassword: 'كلمة المرور الحالية غير صحيحة',
    chooseDesign: 'اختر التصميم',

    // Form fields
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    middleName: 'الاسم الأوسط',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    dateOfBirth: 'تاريخ الميلاد',
    maritalStatus: 'الحالة الاجتماعية',
    single: 'أعزب',
    married: 'متزوج',
    divorced: 'مطلق',
    widowed: 'أرمل',
    nationality: 'الجنسية',
    passportNumber: 'رقم جواز السفر',
    visaStatus: 'حالة التأشيرة',
    visaExpiry: 'انتهاء التأشيرة',
    salary: 'الراتب',
    bankName: 'اسم البنك',
    contractStart: 'بداية العقد',
    contractEnd: 'نهاية العقد',
    contractType: 'نوع العقد',
    permanent: 'دائم',
    contract: 'عقد',
    part_time: 'دوام جزئي',
    temporary: 'مؤقت',
    probation: 'فترة تجربة',
    leaveBalance: 'رصيد الإجازات',
    annualLeave: 'إجازة سنوية',
    sickLeave: 'إجازة مرضية',
    personalLeave: 'إجازة شخصية',
    submit: 'إرسال',
    reset: 'إعادة تعيين',
    requiredField: 'هذا الحقل مطلوب',
    invalidPhone: 'رقم هاتف غير صالح',
    passwordMinLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    confirmPassword: 'تأكيد كلمة المرور',
    passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    logoutConfirmMsg: 'هل أنت متأكد من تسجيل الخروج؟',
    forgotPasswordTitle: 'نسيت كلمة السر؟',
    forgotPasswordStep1: 'أدخل اسم المستخدم للمتابعة',
    forgotPasswordStep2: 'أجب على سؤال الأمان وأدخل كلمة مرور جديدة',
    continueBtn: 'متابعة',
    searchingUser: 'جاري البحث...',
    securityQuestion: 'سؤال الأمان:',
    answer: 'الإجابة',
    answerPlaceholder: 'اكتب إجابتك هنا...',
    securityQ1: 'ما اسم والدتك؟',
    securityQ2: 'ما اسم حيوانك الأليف؟',
    securityQ3: 'ما اسم مدرستك الأولى؟',
    securityQ4: 'ما هو لونك المفضل؟',
    securityQuestionOptionalHint: '(اختياري) حدد سؤال أمان لاستعادة كلمة المرور',
    chooseQuestion: 'اختر سؤالاً',
    chooseSecurityQuestion: 'اختر سؤال الأمان...',
    newPasswordLabel: 'كلمة المرور الجديدة',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    savingPassword: 'جاري الحفظ...',
    resetPassword: 'إعادة تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    changeUsername: 'تغيير اسم المستخدم',
    age: 'العمر',

    // Navigation
    home: 'الرئيسية',
    myProfile: 'ملفي الشخصي',
    myDepartment: 'قسمي',
    myTeam: 'فريقي',
    settings: 'الإعدادات',
    help: 'مساعدة',
    about: 'حول',
    contactUs: 'اتصل بنا',
    feedback: 'ملاحظات',
    notifications: 'الإشعارات',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',

    // Dashboard
    overview: 'نظرة عامة',
    recentActivity: 'النشاط الأخير',
    statistics: 'الإحصائيات',
    reports: 'التقارير',
    manageEmployees: 'إدارة الموظفين',
    departmentDistribution: 'توزيع الأقسام',
    branchDistribution: 'توزيع الفروع',
    monthlyJoinings: 'الانضمامات الشهرية',
    employeeGrowth: 'نمو الموظفين',

    // Table
    noData: 'لا توجد بيانات',
    showing: 'عرض',
    of: 'من',
    entries: 'سجلات',
    rowsPerPage: 'صفوف لكل صفحة',
    page: 'صفحة',
    first: 'الأول',
    last: 'الأخير',

    // Messages
    loginSuccess: 'تم تسجيل الدخول بنجاح',
    loginFailed: 'فشل تسجيل الدخول',
    changePasswordFirst: 'غيّر كلمة المرور',
    changePasswordFirstHint: 'يجب تغيير كلمة المرور قبل المتابعة',
    newPassword: 'كلمة المرور الجديدة',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح',
    searchEmployee: 'بحث عن موظف',
    searchEmployeeHint: 'أدخل اسم الموظف أو كود الموظف لعرض ملفه الشخصي',
    employeeIdOrName: 'اسم الموظف أو كود الموظف',
    searchPlaceholder: 'ابحث بالاسم أو كود الموظف...',
    cannotPreview: 'لا يمكن معاينة هذا الملف',
    openFile: 'فتح الملف',
    noFileAttached: 'لا يوجد ملف مرفق',
    saveSuccess: 'تم الحفظ بنجاح',
    saveFailed: 'فشل الحفظ',
    deleteSuccess: 'تم الحذف بنجاح',
    deleteFailed: 'فشل الحذف',
    updateSuccess: 'تم التحديث بنجاح',
    updateFailed: 'فشل التحديث',
    createSuccess: 'تم الإنشاء بنجاح',
    createFailed: 'فشل الإنشاء',
    importSuccess: 'تم الاستيراد بنجاح',
    importFailed: 'فشل الاستيراد',
    exportSuccess: 'تم التصدير بنجاح',
    exportFailed: 'فشل التصدير',
    backupSuccess: 'تم إنشاء النسخ الاحتياطي بنجاح',
    backupFailed: 'فشل إنشاء النسخ الاحتياطي',
    restoreFailed: 'فشل الاستعادة',

    networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
    serverError: 'خطأ في الخادم. يرجى المحاولة مرة أخرى لاحقاً.',
    unauthorized: 'غير مصرح. يرجى تسجيل الدخول مرة أخرى.',
    forbidden: 'ليس لديك صلاحية لتنفيذ هذا الإجراء.',
    notFound: 'لم يتم العثور على المورد.',

    // Time
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisYear: 'هذا العام',

    // Auth
    sessionExpired: 'انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى.',
    sessionTimeout: 'انتهت المهلة',
    sessionTimeoutHint: 'لم تقم بأي نشاط. سيتم تسجيل خروجك بسبب عدم النشاط.',
    stayLoggedIn: 'البقاء متصلاً',
    invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    accountLocked: 'الحساب مقفل. يرجى الاتصال بالمسؤول.',

    // QR Code
    scanQrCode: 'مسح رمز QR',
    qrCodeDescription: 'امسح رمز QR هذا للوصول بسرعة إلى معلومات الموظف',
    downloadQrCode: 'تنزيل رمز QR',

    // PDF
    generatePdf: 'إنشاء PDF',
    pdfGenerated: 'تم إنشاء PDF بنجاح',
    pdfFailed: 'فشل إنشاء PDF',

    // Print
    printId: 'طباعة بطاقة الهوية',
    idCard: 'بطاقة الهوية',
    companyLogo: 'شعار الشركة',
    employeeSignature: 'توقيع الموظف',
    validUntil: 'صالح حتى',

    // Charts
    chart: 'رسم بياني',
    barChart: 'رسم أعمدة',
    pieChart: 'رسم دائري',
    lineChart: 'رسم خطي',
    noDataAvailable: 'لا توجد بيانات لهذا الرسم البياني',

    // Date & Time
    date: 'التاريخ',
    time: 'الوقت',
    day: 'اليوم',
    month: 'الشهر',
    year: 'السنة',
    start: 'البداية',
    end: 'النهاية',

    // Validation
    fieldRequired: 'هذا الحقل مطلوب',
    invalidFormat: 'تنسيق غير صالح',
    tooShort: 'قصير جداً',
    tooLong: 'طويل جداً',
    minValue: 'الحد الأدنى هو {min}',
    maxValue: 'الحد الأقصى هو {max}',

    // Status
    pending: 'قيد الانتظار',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    cancelled: 'ملغي',
    completed: 'مكتمل',
    inProgress: 'قيد التنفيذ',
    onHold: 'معلق',

    // Misc
    all: 'الكل',
    none: 'لا شيء',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    noResults: 'لم يتم العثور على نتائج',
    tryAgain: 'حاول مرة أخرى',
    viewAll: 'عرض الكل',
    viewDetails: 'عرض التفاصيل',
    collapse: 'طي',
    expand: 'توسيع',
    refresh: 'تحديث',
    retry: 'إعادة المحاولة',
    undo: 'تراجع',
    redo: 'إعادة',
    copy: 'نسخ',
    paste: 'لصق',
    cut: 'قص',
    select: 'تحديد',
    deselect: 'إلغاء التحديد',
    moveUp: 'تحريك لأعلى',
    moveDown: 'تحريك لأسفل',
    dragToReorder: 'اسحب لإعادة الترتيب',
    moreOptions: 'خيارات إضافية',
    lessOptions: 'خيارات أقل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    details: 'التفاصيل',
    summary: 'الملخص',
    fullView: 'عرض كامل',
    compactView: 'عرض مدمج',
    listView: 'عرض القائمة',
    gridView: 'عرض الشبكة',
    sortBy: 'ترتيب حسب',
    ascending: 'تصاعدي',
    descending: 'تنازلي',
    groupBy: 'تجميع حسب',
    enableNotifications: 'تفعيل الإشعارات',
    disableNotifications: 'تعطيل الإشعارات',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    systemDefault: 'إعدادات النظام',
    english: 'الإنجليزية',
    arabic: 'العربية',
    french: 'الفرنسية',
    employeePortal: 'بوابة الموظفين',
    language: 'اللغة',
    theme: 'المظهر',
    profileSettings: 'إعدادات الملف الشخصي',
    notificationSettings: 'إعدادات الإشعارات',
    privacySettings: 'إعدادات الخصوصية',
    securitySettings: 'إعدادات الأمان',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    updateProfile: 'تحديث الملف الشخصي',
    uploadPhoto: 'رفع صورة',
    removePhoto: 'إزالة الصورة',
    cropPhoto: 'قص الصورة',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    rotateLeft: 'تدوير لليسار',
    rotateRight: 'تدوير لليمين',
    resetZoom: 'إعادة تعيين التكبير',
    fitToScreen: 'ملاءمة الشاشة',
    fullscreen: 'ملء الشاشة',
    exitFullscreen: 'الخروج من وضع ملء الشاشة',
    minimise: 'تصغير',
    maximize: 'تكبير',
    restoreDefault: 'استعادة الافتراضي',
    applyChanges: 'تطبيق التغييرات',
    discardChanges: 'تجاهل التغييرات',
    unsavedChanges: 'لديك تغييرات غير محفوظة',
    areYouSure: 'هل أنت متأكد؟',
    thisActionCannotBeUndone: 'لا يمكن التراجع عن هذا الإجراء.',
    permanentAction: 'هذا إجراء دائم.',
    proceedWithCaution: ' proceder con precaución.',
    enterPasswordToConfirm: 'أدخل كلمة المرور للتأكيد.',
    actionRequiresConfirmation: 'يتطلب هذا الإجراء التأكيد.',
    confirmAction: 'تأكيد الإجراء',
    cancelAction: 'إلغاء الإجراء',
    backToTop: 'العودة للأعلى',
    scrollDown: 'تمرير للأسفل',
    goToPage: 'الذهاب إلى الصفحة',
    changePage: 'تغيير الصفحة',
    previousPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    firstPage: 'الصفحة الأولى',
    lastPage: 'الصفحة الأخيرة',
    jumpToPage: 'القفز إلى الصفحة',
    goTo: 'الذهاب إلى',
    ofTotalPages: 'من {total} صفحات',
    selectedRows: '{count} صفوف محددة',
    selectRow: 'تحديد الصف',
    deselectRow: 'إلغاء تحديد الصف',
    expandRow: 'توسيع الصف',
    collapseRow: 'طي الصف',
    viewRow: 'عرض الصف',
    editRow: 'تعديل الصف',
    deleteRow: 'حذف الصف',
    duplicateRow: 'تكرار الصف',
    copyRow: 'نسخ الصف',
    moveRow: 'تحريك الصف',
    rowActions: 'إجراءات الصف',
    bulkActions: 'إجراءات مجمعة',
    noItemsSelected: 'لم يتم تحديد أي عنصر',
    deleteSelected: 'حذف المحدد',
    exportSelected: 'تصدير المحدد',
    printSelected: 'طباعة المحدد',
    selectAction: 'اختر إجراءً',
    confirmBulkDelete: 'هل أنت متأكد من حذف العناصر المحددة؟',
    bulkDeleteSuccess: 'تم حذف العناصر المحددة بنجاح',
    bulkDeleteFailed: 'فشل حذف العناصر المحددة',
    bulkExportSuccess: 'تم تصدير العناصر المحددة بنجاح',
    bulkExportFailed: 'فشل تصدير العناصر المحددة',
    bulkPrintSuccess: 'تم إرسال العناصر المحددة إلى الطابعة',
    bulkPrintFailed: 'فشل طباعة العناصر المحددة',
  },

  fr: {
    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    print: 'Imprimer',
    download: 'Télécharger',
    upload: 'Téléverser',
    export: 'Exporter',
    import: 'Importer',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    close: 'Fermer',
    confirm: 'Confirmer',
    yes: 'Oui',
    no: 'Non',
    actions: 'Actions',

    // Employee Portal
    enterId: "Entrez l'identifiant de l'employé",
    login: 'Connexion',
    attemptsRemaining: 'tentatives restantes',
    lockoutMessage: 'Trop de tentatives échouées. Veuillez patienter 10 minutes.',
    employeeNotFound: 'Employé non trouvé',
    invalidId: "Identifiant d'employé invalide",
    idHelpText: "Entrez votre identifiant d'employé pour accéder à votre profil",
    profile: 'Profil',
    employeeId: "Identifiant de l'employé",
    fullName: 'Nom complet',
    personalInfo: 'Informations personnelles',
    employmentInfo: 'Détails d\'emploi',
    contactInfo: 'Coordonnées',
    jobTitle: 'Titre du poste',
    jobTitleAr: 'Titre du poste (Arabe)',
    jobTitleEn: 'Titre du poste (Anglais)',
    department: 'Département',
    email: 'Email',
    sector: 'Secteur',
    hireDate: "Date d'embauche",
    address: 'Adresse',
    phone: 'Téléphone',
    employmentStatus: "Statut d'emploi",
    active: 'Actif',
    inactive: 'Inactif',
    resigned: 'Démissionné',
    profilePicture: 'Photo de profil',
    fromUrl: 'Depuis un lien',
    qrCode: 'Code QR',
    workShift: 'Quart de travail',
    bloodType: 'Groupe sanguin',
    emergencyContact: "Contact d'urgence",
    notes: 'Notes',
    insuranceNumber: "Numéro d'assurance",
    directManager: 'Manager direct',
    certifications: 'Certifications',
    category: 'Catégorie',
    bank: 'Banque',
    bankAccount: 'Compte bancaire',
    attendanceBase: 'Base de présence',
    route: 'Itinéraire',
    education: 'Formation',
    graduationYear: 'Année de diplôme',
    employmentStartDate: "Date de début d'emploi",
    experience: 'Expérience',
    years: 'Années',
    months: 'Mois',
    days: 'Jours',
    additionalInfo: 'Informations supplémentaires',
    languages: 'Langues',
    selectLanguage: 'Choisir une langue',
    proficiencyLevel: 'Niveau de maîtrise',
    addLanguage: 'Ajouter une langue',
    removeLanguage: 'Supprimer la langue',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    fluent: 'Courant',
    native: 'Langue maternelle',
    documents: 'Documents',
    uploadDocument: 'Téléverser un document',
    addDocument: 'Ajouter un document',
    removeDocument: 'Supprimer le document',
    documentName: 'Nom du document',
    documentType: 'Type de document',
    uploadDate: 'Date de téléversement',
    noDocuments: 'Aucun document téléversé',
    viewDocument: 'Voir',
    supportedFormats: 'Formats supportés: PDF, Word, Excel, Images (JPG, PNG, etc.)',
    copyId: "Copier l'identifiant",
    printProfile: 'Imprimer le profil',
    downloadPdf: 'Télécharger PDF',

    // Admin
    adminLogin: "Connexion administrateur",
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    dashboard: 'Tableau de bord',
    employees: 'Employés',
    addEmployee: 'Ajouter un employé',
    editEmployee: "Modifier l'employé",
    deleteEmployee: "Supprimer l'employé",
    totalEmployees: 'Total des employés',
    activeEmployees: 'Employés actifs',
    inactiveEmployees: 'Employés inactifs',
    departments: 'Départements',
    branches: 'Agences',
    employeesByDepartment: 'Employés par département',
    employeesByBranch: 'Employés par agence',
    activityLog: "Journal d'activité",
    backup: 'Sauvegarde',
    restore: 'Restaurer',
    logout: 'Déconnexion',
    welcome: 'Bienvenue',
    welcomeHint: 'Connectez-vous pour accéder aux données des employés',
    confirmDelete: 'Confirmer la suppression',
    deleteConfirmMessage: "Êtes-vous sûr de vouloir supprimer cet employé ? Cette action est irréversible.",
    sections: 'Sections',
    sectionsSubtitle: 'Gérer les sections auxquelles appartient les employés',
    addSection: 'Ajouter une nouvelle section',
    users: 'Utilisateurs',
    manageUsers: 'Gérer les utilisateurs administrateurs et leurs identifiants',
    addUser: 'Ajouter un utilisateur',
    addNewUser: 'Ajouter un nouvel utilisateur',
    editUser: 'Modifier l\'utilisateur',
    editUsername: 'Modifier le nom d\'utilisateur',
    newUsername: 'Nouveau nom d\'utilisateur',
    enterUsernamePlaceholder: 'Entrez le nom d\'utilisateur...',
    role: 'Rôle',
    selectRole: "Rôle de l'utilisateur",
    superAdmin: 'Super Admin',
    adminUser: 'Admin',
    passwordStatus: 'Statut du mot de passe',
    defaultPasswordBadge: 'Mot de passe par défaut (123456)',
    updatedPasswordBadge: 'Mis à jour',
    createdAt: 'Date de création',
    noUsers: 'Aucun utilisateur trouvé',
    defaultPasswordInfoTitle: 'Mot de passe par défaut : 123456',
    defaultPasswordInfoDesc: 'L\'utilisateur sera invité à changer son mot de passe via un popup lors de sa première connexion.',
    resetPasswordDefault: 'Réinitialiser au mot de passe par défaut',
    resetPasswordConfirmTitle: 'Réinitialiser au mot de passe par défaut',
    resetPasswordConfirmMessage: 'Êtes-vous sûr de vouloir réinitialiser le mot de passe de l\'utilisateur "{username}" par défaut (123456) ?',
    resetPasswordSubtext: 'L\'utilisateur devra définir un nouveau mot de passe lors de sa prochaine connexion.',
    resetPasswordSuccess: 'Mot de passe réinitialisé par défaut (123456) avec succès',
    deleteUserConfirm: 'Êtes-vous sûr de vouloir supprimer l\'utilisateur "{username}" ? Cette action est irréversible.',
    forcedPasswordTitle: 'Changer le mot de passe initial',
    forcedPasswordSubtitle: 'Votre compte nécessite la définition d\'un nouveau mot de passe avant de continuer.',
    newPasswordPlaceholder: 'Entrez le nouveau mot de passe...',
    confirmPasswordPlaceholder: 'Confirmez le nouveau mot de passe...',
    saveAndLogin: 'Enregistrer le mot de passe et continuer',
    backupAndRestore: 'Sauvegarde et restauration',
    backupSubtitle: 'Gérer les sauvegardes de la base de données, exporter et restaurer les données',
    downloadFullBackup: 'Télécharger la sauvegarde complète (.db)',
    downloadJsonBackup: 'Exporter les données en JSON (.json)',
    restoreBackup: 'Restaurer la base de données',
    restoreHint: 'Sélectionnez un fichier de sauvegarde .db valide pour restaurer la base de données',
    selectBackupFile: 'Sélectionner le fichier de sauvegarde',
    confirmRestoreTitle: 'Confirmer la restauration de la base de données',
    confirmRestoreMessage: 'La restauration remplacera toutes les données actuelles. Êtes-vous sûr de vouloir continuer ?',
    backupHistory: "Historique des sauvegardes",
    newUser: 'Nouvel utilisateur',
    sectionNameEn: 'Nom de la section (Anglais)',
    sectionNameAr: 'Nom de la section (Arabe)',
    sectionNameEnPlaceholder: 'ex: IT, HR, Finance',
    sectionNameArPlaceholder: 'ex: تقنية المعلومات، الموارد البشرية',
    noSections: 'Aucune section trouvée',
    deleteSectionConfirm: "Êtes-vous sûr de vouloir supprimer cette section ? Cette action est irréversible.",

    // Custom fields
    customFields: 'Champs personnalisés',
    customFieldsSubtitle: 'Gérer les champs personnalisés affichés dans les profils et l\'export Excel',
    addCustomField: 'Ajouter un champ personnalisé',
    editCustomField: 'Modifier le champ personnalisé',
    fieldNameEn: 'Titre du champ (Anglais)',
    fieldNameAr: 'Titre du champ (Arabe)',
    fieldNameEnPlaceholder: 'ex: Blood Type, National ID',
    fieldNameArPlaceholder: 'مثال: فصيلة الدم، الرقم القومي',
    customFieldType: 'Type de champ',
    customFieldTypeText: 'Texte',
    customFieldTypeNumber: 'Nombre',
    customFieldTypeDate: 'Date',
    customFieldTypeTextarea: 'Texte long',
    customFieldTypeSelect: 'Liste déroulante',
    fieldOptions: 'Options (séparées par des virgules)',
    fieldOptionsPlaceholder: 'ex: Option 1, Option 2, Option 3',
    noCustomFields: 'Aucun champ personnalisé créé',
    deleteCustomFieldConfirm: "Êtes-vous sûr de vouloir supprimer ce champ personnalisé ? Les valeurs enregistrées dans les profils ne seront plus affichées.",
    customFieldSection: 'Section du profil',

    // Profile sections
    profileSections: 'Sections du profil',
    profileSectionsSubtitle: 'Gérer les titres principaux du profil et leur disposition',
    addProfileSection: 'Ajouter une section',
    editProfileSection: 'Modifier la section',
    profileSectionNameEnPlaceholder: 'ex: Certificats, Liens sociaux',
    profileSectionNameArPlaceholder: 'مثال: الشهادات، روابط التواصل',
    sectionColumn: 'Colonne',
    sectionColumnLeft: 'Colonne 1',
    sectionColumnRight: 'Colonne 2',
    sectionSortOrder: 'Ordre',
    sectionType: 'Type',
    sectionBuiltin: 'Intégré',
    sectionCustom: 'Personnalisé',
    sectionBuiltinDeleteError: 'Les sections intégrées ne peuvent pas être supprimées',
    noProfileSections: 'Aucune section de profil trouvée',
    deleteProfileSectionConfirm: "Êtes-vous sûr de vouloir supprimer cette section ? Ses champs personnalisés seront déplacés vers la section par défaut.",

    // Section fields
    sectionFields: 'Champs des sections',
    sectionFieldsSubtitle: 'Ajouter ou supprimer les champs affichés dans chaque section (comme adresse, téléphone, email)',
    addReadyField: 'Ajouter un champ prêt',
    addReadyFieldPlaceholder: 'Sélectionner un champ prêt à ajouter',
    noReadyFields: 'Tous les champs prêts ont été ajoutés à cette section',
    fieldSection: 'Section',
    fieldVisible: 'Visible',
    fieldHidden: 'Masqué',
    builtinField: 'Champ prêt',
    noSectionFields: 'Aucun champ dans cette section',
    deleteSectionFieldConfirm: 'Êtes-vous sûr de vouloir supprimer ce champ de la section ? Il ne sera plus affiché ni modifié dans les formulaires.',
    fieldTypeStatus: 'Statut',
    fieldAlreadyAdded: 'Ce champ est déjà ajouté',

    // Settings
    accountSettings: 'Paramètres du compte',
    changeCredentials: 'Changer les identifiants',
    usernameUpdated: "Nom d'utilisateur mis à jour avec succès",
    passwordUpdated: 'Mot de passe mis à jour avec succès',
    currentPasswordRequired: "Le mot de passe actuel est obligatoire",
    newPasswordRequired: 'Le nouveau mot de passe est obligatoire',
    usernameTaken: "Nom d'utilisateur déjà pris",
    incorrectPassword: 'Mot de passe actuel incorrect',
    chooseDesign: 'Choisir le design',

    // Form fields
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    middleName: 'Deuxième prénom',
    gender: 'Genre',
    male: 'Homme',
    female: 'Femme',
    dateOfBirth: 'Date de naissance',
    maritalStatus: 'État civil',
    single: 'Célibataire',
    married: 'Marié',
    divorced: 'Divorcé',
    widowed: 'Veuf',
    nationality: 'Nationalité',
    passportNumber: 'Numéro de passeport',
    visaStatus: 'Statut du visa',
    visaExpiry: "Expiration du visa",
    salary: 'Salaire',
    bankName: 'Nom de la banque',
    contractStart: 'Début du contrat',
    contractEnd: 'Fin du contrat',
    contractType: 'Type de contrat',
    permanent: 'Permanent',
    contract: 'Contrat',
    part_time: 'Temps partiel',
    temporary: 'Temporaire',
    probation: "Période d'essai",
    leaveBalance: 'Solde de congés',
    annualLeave: 'Congé annuel',
    sickLeave: 'Congé maladie',
    personalLeave: 'Congé personnel',
    submit: 'Soumettre',
    reset: 'Réinitialiser',
    requiredField: 'Champ obligatoire',
    invalidPhone: 'Numéro de téléphone invalide',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    confirmPassword: 'Confirmer le mot de passe',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    forgotPassword: 'Mot de passe oublié ?',
    rememberMe: 'Se souvenir de moi',
    logoutConfirmMsg: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    forgotPasswordTitle: 'Mot de passe oublié ?',
    forgotPasswordStep1: "Entrez votre nom d'utilisateur pour continuer",
    forgotPasswordStep2: 'Répondez à la question de sécurité et entrez un nouveau mot de passe',
    continueBtn: 'Continuer',
    searchingUser: 'Recherche en cours...',
    securityQuestion: 'Question de sécurité :',
    answer: 'Réponse',
    answerPlaceholder: 'Tapez votre réponse ici...',
    securityQ1: "Quel est le nom de votre mère ?",
    securityQ2: "Quel est le nom de votre animal ?",
    securityQ3: "Quel était le nom de votre première école ?",
    securityQ4: "Quelle est votre couleur préférée ?",
    securityQuestionOptionalHint: '(Optionnel) Définir une question de sécurité',
    chooseQuestion: 'Choisir une question',
    chooseSecurityQuestion: 'Choisissez une question de sécurité...',
    newPasswordLabel: 'Nouveau mot de passe',
    confirmPasswordLabel: 'Confirmer le mot de passe',
    savingPassword: 'Enregistrement...',
    resetPassword: 'Réinitialiser le mot de passe',
    backToLogin: 'Retour à la connexion',
    changeUsername: "Changer le nom d'utilisateur",
    age: 'Âge',

    // Navigation
    home: 'Accueil',
    myProfile: 'Mon profil',
    myDepartment: 'Mon département',
    myTeam: 'Mon équipe',
    settings: 'Paramètres',
    help: 'Aide',
    about: 'À propos',
    contactUs: 'Contactez-nous',
    feedback: 'Avis',
    notifications: 'Notifications',
    privacy: 'Politique de confidentialité',
    terms: "Conditions d'utilisation",

    // Dashboard
    overview: 'Aperçu',
    recentActivity: 'Activité récente',
    statistics: 'Statistiques',
    reports: 'Rapports',
    manageEmployees: 'Gérer les employés',
    departmentDistribution: 'Répartition par département',
    branchDistribution: 'Répartition par agence',
    monthlyJoinings: 'Embauches mensuelles',
    employeeGrowth: 'Croissance des employés',

    // Table
    noData: 'Aucune donnée disponible',
    showing: 'Affichage',
    of: 'sur',
    entries: 'entrées',
    rowsPerPage: 'Lignes par page',
    page: 'Page',
    first: 'Premier',
    last: 'Dernier',

    // Messages
    loginSuccess: 'Connexion réussie',
    loginFailed: 'Échec de la connexion',
    changePasswordFirst: 'Changez votre mot de passe',
    changePasswordFirstHint: 'Vous devez changer votre mot de passe avant de continuer',
    newPassword: 'Nouveau mot de passe',
    passwordMismatch: 'Les mots de passe ne correspondent pas',
    passwordChanged: 'Mot de passe modifié avec succès',
    searchEmployee: 'Rechercher un employé',
    searchEmployeeHint: "Entrez le nom ou l'identifiant de l'employé pour voir son profil",
    employeeIdOrName: "Nom ou identifiant de l'employé",
    searchPlaceholder: "Rechercher par nom ou identifiant d'employé...",
    cannotPreview: 'Impossible de prévisualiser ce fichier',
    openFile: 'Ouvrir le fichier',
    noFileAttached: 'Aucun fichier joint',
    saveSuccess: 'Enregistré avec succès',
    saveFailed: "Échec de l'enregistrement",
    deleteSuccess: 'Supprimé avec succès',
    deleteFailed: 'Échec de la suppression',
    updateSuccess: 'Mis à jour avec succès',
    updateFailed: 'Échec de la mise à jour',
    createSuccess: 'Créé avec succès',
    createFailed: 'Échec de la création',
    importSuccess: 'Importé avec succès',
    importFailed: "Échec de l'importation",
    exportSuccess: 'Exporté avec succès',
    exportFailed: "Échec de l'exportation",
    backupSuccess: 'Sauvegarde créée avec succès',
    backupFailed: 'Échec de la création de la sauvegarde',
    restoreSuccess: 'Restauré avec succès',
    restoreFailed: 'Échec de la restauration',
    networkError: 'Erreur réseau. Vérifiez votre connexion.',
    serverError: 'Erreur serveur. Veuillez réessayer plus tard.',
    unauthorized: 'Non autorisé. Veuillez vous reconnecter.',
    forbidden: "Vous n'avez pas la permission d'effectuer cette action.",
    notFound: 'Ressource non trouvée.',

    // Time
    today: "Aujourd'hui",
    yesterday: 'Hier',
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois-ci',
    thisYear: 'Cette année',

    // Auth
    sessionExpired: 'Votre session a expiré. Veuillez vous reconnecter.',
    sessionTimeout: 'Temps mort de session',
    sessionTimeoutHint: 'Vous avez été inactif. Vous serez déconnecté en raison de l inactivité.',
    stayLoggedIn: 'Rester connecté',
    invalidCredentials: "Nom d'utilisateur ou mot de passe invalide",
    accountLocked: 'Compte verrouillé. Contactez l administrateur.',

    // QR Code
    scanQrCode: 'Scanner le code QR',
    qrCodeDescription: 'Scannez ce code QR pour accéder rapidement aux informations de l employé',
    downloadQrCode: 'Télécharger le code QR',

    // PDF
    generatePdf: 'Générer PDF',
    pdfGenerated: 'PDF généré avec succès',
    pdfFailed: 'Échec de la génération du PDF',

    // Print
    printId: "Imprimer la carte d'identité",
    idCard: "Carte d'identité",
    companyLogo: 'Logo de l\'entreprise',
    employeeSignature: "Signature de l'employé",
    validUntil: 'Valable jusqu\'au',

    // Charts
    chart: 'Graphique',
    barChart: 'Graphique à barres',
    pieChart: 'Graphique circulaire',
    lineChart: 'Graphique linéaire',
    noDataAvailable: 'Aucune donnée disponible pour ce graphique',

    // Date & Time
    date: 'Date',
    time: 'Heure',
    day: 'Jour',
    month: 'Mois',
    year: 'Année',
    start: 'Début',
    end: 'Fin',

    // Validation
    fieldRequired: 'Ce champ est obligatoire',
    invalidFormat: 'Format invalide',
    tooShort: 'Trop court',
    tooLong: 'Trop long',
    minValue: 'La valeur minimale est {min}',
    maxValue: 'La valeur maximale est {max}',

    // Status
    pending: 'En attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    cancelled: 'Annulé',
    completed: 'Terminé',
    inProgress: 'En cours',
    onHold: 'En attente',

    // Misc
    all: 'Tout',
    none: 'Aucun',
    selectAll: 'Tout sélectionner',
    deselectAll: 'Tout désélectionner',
    noResults: 'Aucun résultat trouvé',
    tryAgain: 'Réessayer',
    viewAll: 'Voir tout',
    viewDetails: 'Voir les détails',
    collapse: 'Réduire',
    expand: 'Développer',
    refresh: 'Actualiser',
    retry: 'Réessayer',
    undo: 'Annuler',
    redo: 'Rétablir',
    copy: 'Copier',
    paste: 'Coller',
    cut: 'Couper',
    select: 'Sélectionner',
    deselect: 'Désélectionner',
    moveUp: 'Déplacer vers le haut',
    moveDown: 'Déplacer vers le bas',
    dragToReorder: 'Faites glisser pour réorganiser',
    moreOptions: "Plus d'options",
    lessOptions: "Moins d'options",
    showMore: 'Afficher plus',
    showLess: 'Afficher moins',
    details: 'Détails',
    summary: 'Résumé',
    fullView: 'Vue complète',
    compactView: 'Vue compacte',
    listView: 'Vue en liste',
    gridView: 'Vue en grille',
    sortBy: 'Trier par',
    ascending: 'Croissant',
    descending: 'Décroissant',
    groupBy: 'Grouper par',
    enableNotifications: 'Activer les notifications',
    disableNotifications: 'Désactiver les notifications',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    systemDefault: 'Par défaut',
    english: 'Anglais',
    arabic: 'Arabe',
    french: 'Français',
    employeePortal: 'Portail des employés',
    language: 'Langue',
    theme: 'Thème',
    profileSettings: 'Paramètres du profil',
    notificationSettings: 'Paramètres de notification',
    privacySettings: 'Paramètres de confidentialité',
    securitySettings: 'Paramètres de sécurité',
    changePassword: 'Changer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    updateProfile: 'Mettre à jour le profil',
    uploadPhoto: 'Téléverser une photo',
    removePhoto: 'Supprimer la photo',
    cropPhoto: 'Recadrer la photo',
    zoomIn: 'Zoom avant',
    zoomOut: 'Zoom arrière',
    rotateLeft: 'Tourner à gauche',
    rotateRight: 'Tourner à droite',
    resetZoom: 'Réinitialiser le zoom',
    fitToScreen: 'Ajuster à l\'écran',
    fullscreen: 'Plein écran',
    exitFullscreen: 'Quitter le plein écran',
    minimise: 'Minimiser',
    maximize: 'Maximiser',
    restoreDefault: 'Restaurer par défaut',
    applyChanges: 'Appliquer les modifications',
    discardChanges: 'Ignorer les modifications',
    unsavedChanges: 'Vous avez des modifications non enregistrées',
    areYouSure: 'Êtes-vous sûr ?',
    thisActionCannotBeUndone: 'Cette action est irréversible.',
    permanentAction: 'C\'est une action permanente.',
    proceedWithCaution: 'Procédez avec prudence.',
    enterPasswordToConfirm: 'Entrez votre mot de passe pour confirmer.',
    actionRequiresConfirmation: 'Cette action nécessite une confirmation.',
    confirmAction: 'Confirmer l\'action',
    cancelAction: 'Annuler l\'action',
    backToTop: 'Retour en haut',
    scrollDown: 'Défiler vers le bas',
    goToPage: 'Aller à la page',
    changePage: 'Changer de page',
    previousPage: 'Page précédente',
    nextPage: 'Page suivante',
    firstPage: 'Première page',
    lastPage: 'Dernière page',
    jumpToPage: 'Aller à la page',
    goTo: 'Aller à',
    ofTotalPages: 'sur {total} pages',
    selectedRows: '{count} lignes sélectionnées',
    selectRow: 'Sélectionner la ligne',
    deselectRow: 'Désélectionner la ligne',
    expandRow: 'Développer la ligne',
    collapseRow: 'Réduire la ligne',
    viewRow: 'Voir la ligne',
    editRow: 'Modifier la ligne',
    deleteRow: 'Supprimer la ligne',
    duplicateRow: 'Dupliquer la ligne',
    copyRow: 'Copier la ligne',
    moveRow: 'Déplacer la ligne',
    rowActions: 'Actions de la ligne',
    bulkActions: 'Actions groupées',
    noItemsSelected: 'Aucun élément sélectionné',
    deleteSelected: 'Supprimer la sélection',
    exportSelected: 'Exporter la sélection',
    printSelected: 'Imprimer la sélection',
    selectAction: 'Choisir une action',
    confirmBulkDelete: 'Êtes-vous sûr de vouloir supprimer les éléments sélectionnés ?',
    bulkDeleteSuccess: 'Éléments sélectionnés supprimés avec succès',
    bulkDeleteFailed: 'Échec de la suppression des éléments sélectionnés',
    bulkExportSuccess: 'Éléments sélectionnés exportés avec succès',
    bulkExportFailed: "Échec de l'exportation des éléments sélectionnés",
    bulkPrintSuccess: 'Éléments sélectionnés envoyés à l\'imprimante',
    bulkPrintFailed: 'Échec de l\'impression des éléments sélectionnés',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'
  })

  const toggleLanguage = () => {
    setLanguage(prev => {
      if (prev === 'en') return 'ar'
      if (prev === 'ar') return 'fr'
      return 'en'
    })
  }

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.en[key] || key
    Object.entries(params).forEach(([param, value]) => {
      text = text.replace(`{${param}}`, value)
    })
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
